### PR TITLE
Added content for all tweets and retweets which have happened on ETH_Network since the automation started on September 8th.

### PR DESCRIPTION
**Pull request by bobsummerwill**
Added content for all tweets and retweets which have happened on ETH_Network since the automation started on September 8th.

Various tweets and retweets had been made directly, outside of this automated workflow, meaning we had lost revision history here. When this is merged we will end up with some duplicates, but can tidy them up on the other side, getting us back into a clean state. Updated the examples and the README *not* to use eth_classic, because we are intentionally moving away from that. Removed TestRetweet, which should not have been committed. Removed "Why" tweet, because there was a "WhyClassic" at the exact same time.  Duplicated.

Two of the reply tweets are missing images/GIFs versus the directly posted versions.   Need to work out how to add those in.

### CODE REVIEW

**Comment by bobsummerwill** [comment]
@IstoraMandiri So the ChuckSRQ history there is a bit of a mess.

Are edits to existing "tweet" files not noticed by the automation?
So you had to keep making new filenames for them to be actioned?
Like - it is a one-shot deal on these files?

If so, we could at least deleted those two older versions out without any damage, to make it clearer.
But not rename, because that would trigger a fresh retweet.

(Aside - merging this will retweet/re-reply to everything, but then at least we have the history and can manually clean up on the other side).

And from there, try always to stick to the Github flow, for ease of papertrail.

**Comment by bobsummerwill** [comment]
@IstoraMandiri Just pushed a commit into this PR with those deletions.

**Comment by gitr0n1n** [comment]
> @IstoraMandiri So the ChuckSRQ history there is a bit of a mess.
> 
> Are edits to existing "tweet" files not noticed by the automation? So you had to keep making new filenames for them to be actioned? Like - it is a one-shot deal on these files?
> 
> If so, we could at least deleted those two older versions out without any damage, to make it clearer. But not rename, because that would trigger a fresh retweet.
> 
> (Aside - merging this will retweet/re-reply to everything, but then at least we have the history and can manually clean up on the other side).
> 
> And from there, try always to stick to the Github flow, for ease of papertrail.

So @IstoraMandiri is learning the limitations of the Twitter Together right now. There will likely be a lot of manual tweets by me until we figute the work arounds, example- we don't know how to add a picture to a tweet or delete a tweet. So those tweets need me to log in post them. right now. Please remember we are in early beta stage. By the time I convert this account to a shared email, we will have ironed out all these learning pains. So I don't think it is super important to focus on have a history of every tweet in here right now, as I will be for sure logging in to tweet some more on this account during this process. At the decentralization transfer, i think it makes sense to do this clean up though.

**Comment by IstoraMandiri** [comment]
Thanks for the comments Bob.

Yes, the twitter-together codebase is fairly limited / not tested, and we are using an [experimental](https://github.com/twitter-together/action/pull/177) fork to enable rewteets that has proven [quite](#39) [fickle](#57), but next week I hope to make some improvements to fix the rough edges.

It is very much testing in production both in code and social / contributions workflow.

Also, looks like a bunch has been merged upstream recently which I'll need to check out. https://github.com/twitter-together/action/pulls?q=is%3Apr+is%3Aclosed

> Are edits to existing "tweet" files not noticed by the automation? So you had to keep making new filenames for them to be actioned? Like - it is a one-shot deal on these files?

Yes, that's correct. Twitter-together only detects newly added files via `git`, not renames / updates. 

FYI we also need to be [careful]() about renames and how git detects these so they are not accidentally re-tweeted. 

Planning to document all this properly once we get our workflow sorted.

> If so, we could at least deleted those two older versions out without any damage, to make it clearer. But not rename, because that would trigger a fresh retweet.

Yes, I was planning to clean these up next week when I spend more time on this, but as this repo was intended to be for testing I was keeping them around for reference until we nail down a process for dealing with these cases, which depends on what I can do in terms of improvements with twitter-together.

As for merging a copy of the tweets the @gitr0n1n made manually, this should probably be done elsewhere (or by some other format than files ending in `tweet`), as they will trigger them to be tweeted again by this repo once again at the time this PR is merged (so please don't merge these changes), and will be confusing for people who have already commented. 

As @gitr0n1n mentioned, the intent was to get to a point where were a happy with our workflow and then fully switch to only tweeting from this repo, at which point the history would be maintained. Until thenm as far as @gitr0n1n making manual tweets, I agree it should be avoided, but during this testing phase  due to errors / lack of engagement in this repo, seemed like a reasonable stop gap. 

Changes to the examples to ETC_Network make sense.

**Comment by bobsummerwill** [comment]
OK - trimmed all those "retroactive" ones back out.
Was a useful learning exercise.

**Review by IstoraMandiri — APPROVED** [review]

**Pull request merged**
