### PR TITLE
Proposing the fixed announcement for CommunityNFT contract deployment

### PR DESCRIPTION
**Pull request by Dexaran**

### CODE REVIEW

**Review by w1g0 — APPROVED** [review]

**Review by gitr0n1n — CHANGES_REQUESTED** [review]
This retweeted tweet isn't loading for me for reveiw, Anyone else experiencing a dead link?

https://twitter.com/Dexaran/status/1567900923279835136

Pulled from Dexaran's feed, links match. Weird- not sure why it wasn't loading in any browser for me.
https://twitter.com/Dexaran/status/1567900923279835136

**Comment by Dexaran** [comment]
> This retweeted tweet isn't loading for me for reveiw, Anyone else experiencing a dead link?
> 
> https://twitter.com/Dexaran/status/1567900923279835136

checked from mobile - it seems that everything works fine for me

**Comment by w1g0** [comment]
> This retweeted tweet isn't loading for me for reveiw, Anyone else experiencing a dead link?
> 
> https://twitter.com/Dexaran/status/1567900923279835136
> 
> Pulled from Dexaran's feed, links match. Weird- not sure why it wasn't loading in any browser for me. https://twitter.com/Dexaran/status/1567900923279835136

It doesn't seem to load on PC, same issue here.

**Review by gitr0n1n — DISMISSED** [review]
LGTM

**Comment by gitr0n1n** [comment]
> > This retweeted tweet isn't loading for me for reveiw, Anyone else experiencing a dead link?
> > https://twitter.com/Dexaran/status/1567900923279835136
> > Pulled from Dexaran's feed, links match. Weird- not sure why it wasn't loading in any browser for me. https://twitter.com/Dexaran/status/1567900923279835136
> 
> It doesn't seem to load on PC, same issue here.

yeah i'm on PC as well.

**Comment by gitr0n1n** [comment]
> > This retweeted tweet isn't loading for me for reveiw, Anyone else experiencing a dead link?
> > https://twitter.com/Dexaran/status/1567900923279835136
> 
> checked from mobile - it seems that everything works fine for me

Did you adjust something? it appears to be loading now. Strange.

**Review by gitr0n1n — APPROVED** [review]
Odd error where the retweet link is spotty on loading on PC.

Confirmed the link is accurate. Not sure why we are seeing this, but everything checks out on deep review. Let's give it a shot to push it through and if its broken we can resolve.

**Comment by gitr0n1n** [comment]
Appears to have worked

https://twitter.com/ETC_Network/status/1567935931176321029

**Comment by w1g0** [comment]
While it shouldn't... 👉 https://github.com/ethereumclassic/twitter-together/issues/19

**Comment by IstoraMandiri** [comment]
This tweet's formatting was incorrect.

It should be

```
---
retweet: blah
---

Text
````

Instead it was

```
retweet: blah

Text
```

Hence you an see "retweet" at the top of the tweet when it was published.

**Pull request merged**
