### PR TITLE
Create 2022_09_09_SoyFinance_retweet.tweet

### PR DESCRIPTION
**Pull request by ReallyMadCatter**

### CODE REVIEW

**Review by w1g0 — COMMENTED** [review]
Currently we are trying to achieve consensus about which projects can be retweeted. One thing what was mentioned is that the project needs to be listed here https://ethereumclassic.org/services

**Comment by brolal** [comment]
Yeah, we need to make some guide lines regarding publishing projects. For example, only projects listed on etc.org can submit, just to add a layer.

**Comment by w1g0** [comment]
So @ReallyMadCatter, the indirect message is to create a PR on https://github.com/ethereumclassic/ethereumclassic.github.io/pulls for your product to be added on the ETC website.

**Comment by ReallyMadCatter** [comment]
Soy Finance was listed on ETC Apps page today, but the tweet is outdated, so closing PR. @brolal @w1g0 Thank you very much guys!

**Comment by w1g0** [comment]
Thank you for creating the PR @ReallyMadCatter 🙏
It's great to see community interest!

**Pull request closed without merging**
