### PR TITLE
Add husky for counting tweet chars on pre-commit hook

### PR DESCRIPTION
**Pull request by ziogaschr**
This is just a start for applying simple rules pre-commit.
For example, I have added counting of chars in a tweet, skipping replies and retweets as they have a header in the file (we can make it work too). 

What do you think?

### CODE REVIEW

**Comment by brolal** [comment]
I was thinking about this, guess you all ready made it

**Comment by ziogaschr** [comment]
Yes, you can review it here

**Comment by brolal** [comment]
it has a dependency error, also:
Screenshot from 2022-09-11 16-49-52

**Comment by brolal** [comment]
Is is possible to use husky to parse the actual tweet on discord, without using a third party app like zapier.com or automate.io?

**Review by gitr0n1n — APPROVED** [review]

**Comment by gitr0n1n** [comment]
@IstoraMandiri notice- when i approve a PR, then revoke my approval. It still counts the approval.

**Comment by ziogaschr** [comment]
> Is is possible to use husky to parse the actual tweet on discord, without using a third party app like zapier.com or automate.io?

I don't think that's possible in the context of this PR. 
This PR checks the length before the commit to the repo happens (which requires `husky` to be installed).
What you describe is probably after the PR has been merged and the tweet happened.

Please, let me know if I understood your comment wrong. If the flow you describe is correct, then it might be better to check the actual thing as you describe

**Comment by ziogaschr** [comment]
Will try to fix the failing checks tomorrow.

**Comment by brolal** [comment]
Yeah, I want the payload after the PR... for a the community, off course. We have 15k dudes on discord, so if there is a possibility to serve them with etc_network content, without clicking, that would be cool

**Comment by ziogaschr** [comment]
I think it worths making this a new issue

**Comment by brolal** [comment]
I agree... I would make it if I know how

**Comment by ziogaschr** [comment]
I handled the peer dependency error with https://github.com/ethereumclassic/twitter-together/pull/34/commits/99a41024057b67a36528d71f27d9a7b7f4879c1a

**Comment by IstoraMandiri** [comment]
I will review this shortly, and can see the benefit.

FYI the `twitter-together` app does already have a PR check for ensuring the length is correct, but only does this on PR and not on commit. 

Also, does this strip away the `---` headers?  Looking at it now the regex does not, but I guess it can.

**Comment by ziogaschr** [comment]
Oh, I didn't know that it does on PR level.
If it does and if husky won't be used for other use cases, then I might close this PR. My only worry is that someone offline, has to do 'npm install' for doing a commit. 

If you decide to approve/merge this, then I will have a look at removing the headers as well.

**Comment by IstoraMandiri** [comment]
As there's been a bunch of work going on in the twitter-together library, including improving pre-merge preview checks, I think we should focus efforts there rather than using husky. 

Nevertheless, your contribution is very much appreciated.

**Comment by ziogaschr** [comment]
@IstoraMandiri sure, makes sense as checks are in place pre-merge.

**Pull request closed without merging**
