### PR TITLE
Create 14-09-2022_SoyFinance_ETC_Services_Listing.tweet

### PR DESCRIPTION
**Pull request by ReallyMadCatter**
Retweet of a Soy Finance tweet about its listing on ETC Apps and Services Page.

### CODE REVIEW

**Review by w1g0 — APPROVED** [review]

**Comment by IstoraMandiri** [comment]
@w1g0 in future before approving, we should make sure the checks have been run and the preview is giving expected output

**Comment by IstoraMandiri** [comment]
Also, I think this is a good approach to promoting projects, by retweeting their tweets it means there is cross promotion of both the app and the website and the twitter handles. As long as they link to the etc.org website, and they don't have excessive promotion, I think this is great.

FWIW, it is possible to link via the website directly to the app via https://ethereumclassic.org/services/apps#2022-09-12-soyfinance

**Comment by IstoraMandiri** [comment]
Before I approve this and the general approach would be good to hear some other's input @brolal @gitr0n1n 

The one downside is being seen as promoting potential scam projects.

**Comment by w1g0** [comment]
As this is a decentralized, community driven account. There's always the risk of promoting scammy projects. But most projects will start with good intentions and then panic when something goes wrong and pull the rug. The reflex of community members should be to interact in the comment section and see what others say with reputable credentials. Until then I'm prone to give most projects the benefit of the doubt without endorsing them. If someone knows that a project is a scam they should comment on the PR to prevent the tweet going live. Just my 2 gwei on this. But ye, I would love to hear other opinions.

**Comment by w1g0** [comment]
> @w1g0 in future before approving, we should make sure the checks have been run and the preview is giving expected output

The format and the link to the tweet was checked, @IstoraMandiri how do I run the preview?

**Comment by IstoraMandiri** [comment]
I ran it this time (this is only needed for new contributors), but you can trigger it  from the 'actions' menu.

**Comment by IstoraMandiri** [comment]
As long as the tweet only links to the website, people will see the disclaimer so I am pretty comfortable with this approach.

Waiting to hear other's opinions though before merging this. @brolal @gitr0n1n @bobsummerwill etc.

**Pull request closed without merging**
