### PR TITLE
Create 2022_09_08_LetItBeKnown.tweet

### PR DESCRIPTION
**Pull request by Soteria-Smart-Contracts**

### CODE REVIEW

**Review by w1g0 — APPROVED** [review]

**Comment by IstoraMandiri** [comment]
Please ensure the filename is correctly formatted, i.e. 2022_09_08...

**Comment by Soteria-Smart-Contracts** [comment]
Fixed @IstoraMandiri

**Review by gitr0n1n — APPROVED** [review]

**Comment by IstoraMandiri** [comment]
The line breaks here are weird, shouldn't it be one line?

In any case, i'll merge this to see what happens!

**Comment by IstoraMandiri** [comment]
Yes, as anticipated, the line breaks in this PR didn't render as intended on twitter.

Good one to note for future reviews, and style guides.

https://twitter.com/ETC_Network/status/1568091745249886208

**Pull request merged**
